### ISSUE TITLE
#11 installation issues on Mac

### ISSUE THREAD

**Issue by Daniyal-Warraich** [cfenollosa/os-tutorial#218] opened 2021-08-15 04:32 UTC
I successfully manage to get to the last line of installation of the `binutils` part: `make all install 2>&1 | tee make.log`. It runs, but it exits with an error:
```
*** BFD does not support target arm-apple-darwin20.6.0.
*** Look in bfd/config.bfd for supported targets.
make[1]: *** [configure-bfd] Error 1
make: *** [all] Error 2
```
I have no clue how to fix it.

**Comment by Daniyal-Warraich** [comment] 2021-08-15 23:18
Update: I managed to get past that part, but now I get permission errors, saying I cannot create the directory `user/local/i386elf`

**Comment by BetaPictoris** [comment] 2021-08-17 06:52
Are you running it through macOS or something like Brunch?

**Comment by Daniyal-Warraich** [comment] 2021-08-17 06:57
@BetaPictoris yes, through macOS.

**Comment by BetaPictoris** [comment] 2021-08-19 16:55
> @BetaPictoris yes, through macOS.

What are you using then?

**Comment by Daniyal-Warraich** [comment] 2021-08-19 18:06
I am using Mac, running macOS

**Comment by BetaPictoris** [comment] 2021-08-19 18:31
> @BetaPictoris I am using Mac, running macOS

Sorry, macOS is not supported.

**Comment by Daniyal-Warraich** [comment] 2021-08-20 01:51
@BetaPictoris Is there an alternative or any other way to be able to compile the kernel?

**Comment by BetaPictoris** [comment] 2021-08-20 06:21
> @BetaPictoris Is there an alternative or any other way to be able to compile the kernel?

Sorry, I thought this was a different issue. 

I think this might be a duplicate of #212.

**Comment by Daniyal-Warraich** [comment] 2021-09-05 04:08
@BetaPictoris is there any way without installing another operating system

**Comment by BetaPictoris** [comment] 2021-09-05 04:22
> @BetaPictoris is there any way without installing another operating system

https://github.com/cfenollosa/os-tutorial/issues/212#issuecomment-864470330

**Comment by Daniyal-Warraich** [comment] 2021-09-05 04:28
@BetaPictoris about that comment you showed me; How do I disable system integrity protection in recovery mode terminal?

**Comment by BetaPictoris** [comment] 2021-09-05 15:14
> @BetaPictoris about that comment you showed me; How do I disable system integrity protection in recovery mode terminal?

Look at [this](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection).

**Comment by Daniyal-Warraich** [comment] 2021-09-06 18:47
@BetaPictoris Thank you.

**Closed** 2021-09-06 18:47 UTC
